apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  selector:
    matchLabels:
      app: ping-pong

  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: ping-pongs
          persistentVolumeClaim:
            claimName: pingpong-pvc
      containers:
        - name: ping-pong
          image: buddy00/ping-pong:0.2.0
          volumeMounts:
            - mountPath: /mnt/data
              name: ping-pongs
          env:
            - name: PORT
              value: "3000"
