# https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ping-pong-stset
  namespace: exercises
spec:
  serviceName: ping-pong-svc
  selector:
    matchLabels:
      app: ping-pong
  replicas: 1
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: pingpong
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: sekret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: postgres
              name: postgres-data-storage
        - name: ping-pong-backend
          image: buddy00/ping-pong@sha256:ee7b2a2c7510e16ad74440c22657e69baf1ab5cb416f5793d9da5b7da96b72f9
          volumeMounts:
            - mountPath: /mnt/data
              name: postgres-data-storage
          env:
            - name: DB_HOST
              value: localhost
            - name: DB_USER
              value: myuser
            - name: DB_PASSWORD
              value: sekret
            - name: DB_NAME
              value: pingpong
            - name: DB_PORT
              value: "5432"
            - name: PORT
              value: "3000"
  volumeClaimTemplates:
    - metadata:
        name: postgres-data-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: ping-pong-svc
spec:
  # type: NodePort
  clusterIP: None
  ports:
    - port: 3000
    # - port: 80
    # protocol: TCP
    # targetPort: 3000
  selector:
    app: ping-pong
