# https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ping-pong-stset
  namespace: exercises
spec:
  serviceName: ping-pong-svc
  selector:
    matchLabels:
      app: ping-pong
  replicas: 1
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: pingpong
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: sekret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
              subPath: postgres
        - name: ping-pong-backend
          image: buddy00/ping-pong:0.7.0
          env:
            - name: DB_HOST
              value: localhost
            - name: DB_USER
              value: myuser
            - name: DB_PASSWORD
              value: sekret
            - name: DB_NAME
              value: pingpong
            - name: DB_PORT
              value: "5432"
            - name: PORT
              value: "3000"
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /ready
              port: 3000
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: ping-pong-svc
spec:
  # type: NodePort
  clusterIP: None
  ports:
    - port: 3000
    # - port: 80
    # protocol: TCP
    # targetPort: 3000
  selector:
    app: ping-pong
