# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
        - name: file-content
          configMap:
            name: log-config
            items:
              - key: information.txt
                path: information.txt
        # - name: ping-pongs
        #   persistentVolumeClaim:
        #     claimName: pingpong-pvc
      containers:
        - name: log-output
          image: buddy00/log-output:0.3.0
          volumeMounts:
            - name: shared-logs
              mountPath: /mnt/shared
        - name: log-output-server
          image: buddy00/log-output-server@sha256:ea028feadde0bc0ae18a8133635e71d3f805cb04c3f7eabca9dac1ea62f2c387
          env:
            - name: PORT
              value: "3002"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-config
                  key: MESSAGE

          volumeMounts:
            - name: shared-logs
              mountPath: /mnt/shared
            - name: file-content
              mountPath: /mnt/config
            # - name: ping-pongs
            #   mountPath: /mnt/data
