apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-backend
spec:
  selector:
    matchLabels:
      app: todo-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: buddy00/todo-backend@sha256:4df102f9ec24a73946d57ab2cb6fafa1b9d40259e64ca0d8db79a0bb3e992e09
          env:
            - name: PORT
              value: "3001"
