apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: todo-backend-svc
spec:
  selector:
    app: todo-backend
  clusterIP: None
  ports:
    - port: 3001
      name: todo-backend
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-backend
  namespace: project
spec:
  serviceName: "todo-backend-svc"
  selector:
    matchLabels:
      app: todo-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: buddy00/todo-backend:0.2.0
          ports:
            - containerPort: 3001
              name: todo-backend
          env:
            - name: PORT
              value: "3001"
            - name: MONGODB_URI
              value: "mongodb://root:sekret@localhost:27017/"
        - name: mongo
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: sekret
  volumeClaimTemplates:
    - metadata:
        name: mongo-data-storage
      spec:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
